name: Generate GitHub Streak Stats

on:
  schedule:
    - cron: '0 */1 * * *'  # Every hour
  workflow_dispatch:       # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Download streak SVG
        run: |
          curl -o streak-stats.svg "https://streak-stats.demolab.com?user=amira630&theme=default"

      - name: Commit and push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p images
          mv streak-stats.svg images/streak-stats.svg
          git add images/streak-stats.svg
          git commit -m "Update streak stats SVG"
          git push
